### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by anubi** [5uru/Speak#2]
Hi,

I was able to download, install and startup the server. But I was a little underwhelmed by the results? I tried speaking Spanish and Japanese and the model inaccurately interpreted what I'd said? I'm not entirely sure how to use this properly. Is there another readme somewhere that better describes the intended basic use case?

**Comment by 5uru** [comment]
Hi @anubi ,

Thank you for your feedback! I acknowledge the issues with language interpretation you've encountered; the current version is in alpha and has limited multilingual support.

I'm planning to develop the project from scratch, focusing on improving installation and enhancing language capabilities. Updated documentation and a more user-friendly setup are also on the agenda.

Your input is invaluable, and I invite any further suggestions. Stay tuned for updates, and thank you for contributing to the project's improvement.
